// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ6piwnInDam3UokSLv6_Q-RrSNIvcBt8',
    appId: '1:843262522577:web:86a06468d4e95d514181f0',
    messagingSenderId: '843262522577',
    projectId: 'irfanacademy',
    authDomain: 'irfanacademy.firebaseapp.com',
    storageBucket: 'irfanacademy.firebasestorage.app',
    measurementId: 'G-6TG24V8H9L',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_lnWuXFyn0aFaH7-ziT1p4mNCEuoCgjs',
    appId: '1:843262522577:ios:3614e9f89017ac204181f0',
    messagingSenderId: '843262522577',
    projectId: 'irfanacademy',
    storageBucket: 'irfanacademy.firebasestorage.app',
    iosBundleId: 'com.example.irfanAcademy',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4sAyTido8QDazG5KHqk_HntW04IuuJpg',
    appId: '1:843262522577:android:37af2a3518377a214181f0',
    messagingSenderId: '843262522577',
    projectId: 'irfanacademy',
    storageBucket: 'irfanacademy.firebasestorage.app',
  );
}
